### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by adriandiglio**
Uploading picture to describe the workflow.

### CODE REVIEW

**Review by xee5ch — COMMENTED** [review]
Hello, random community member here. :wave: I think it would be helpful to adapt the BloSS@M material to this particular use case and GitHub directly renders the Mermaid diagram syntax into GitHub directly if you embed it into any Markdown file.

Would you want help with that? The use case is a little different, so it is confusing for me as an observer and potential future contributor how the previous OSCAL work fits. I would love to help change that if I may.

**Comment by adriandiglio** [comment]
Hi @xee5ch! Yes, we would happily welcome your help with that 👍. For reference, I created this other PR (https://github.com/ossf/S2C2F-attestation-schema-and-tool/pull/31) to capture our Roadmap of this tool, which is the markdown page where this picture was going to live (and also appropriately credits/references the BloSS@M material). 

We got started in this repo trying to use OSCAL as an attestation format for S2C2F compliance, though we had trouble getting our OSCAL Catalog file to validate. If possible, I would welcome your expertise and thoughts on path forward.

CC: @yogitasrivastava

**Comment by xee5ch** [comment]
As a next step we could either finish quick review on this, merge, and go for a second iteration or modify this in place. What would you all prefer? In the interim we can probably use something like [mermaid.live](https://mermaid.live) to get things started. I actually wanted to draw out my understanding and check alignment with you as I am worried I might misunderstand and lead you all astray.

**Comment by adriandiglio** [comment]
Agree. I think a quick review + merge just to get something basic posted would be good. Then we could iterate on a much more specific flow diagram tailored to this project's goals. I think mermaid.live seems well suited for that :). I'll reach out to you on slack so we can align

**Review by xee5ch — APPROVED** [review]
In the vein of https://github.com/ossf/S2C2F-attestation-schema-and-tool/pull/30#issuecomment-1943062100, I now approve. I hope this helps move forward future work we outlined in the comment. :smile:

**Review by camaleon2016 — APPROVED** [review]

**Pull request merged**
