### PR TITLE
Adding github action, component definition, schema

### PR DESCRIPTION
**Pull request by anandchugh**
Adding github action
Adding component definition
Adding component schema
Adding demo python app which hits http end point and need python `requests` package from pypi.org

### CODE REVIEW

**Comment by adriandiglio** [comment]
@anandchugh what is the DCO check that was not successful? I haven't seen that before.

**Comment by anandchugh** [comment]
> @anandchugh what is the DCO check that was not successful? I haven't seen that before.

Fixed DCO([Developer Certificate of Origin](https://developercertificate.org/)) issue, it says we need to signoff each commit.
Quick way to signoff each commit by using `git commit -s` command 
Or we can add following in commit message
```This is my commit message

Signed-off-by: Random J Developer <random@developer.example.org>```

**Comment by anandchugh** [comment]
> > @anandchugh what is the DCO check that was not successful? I haven't seen that before.
> 
> Fixed DCO([Developer Certificate of Origin](https://developercertificate.org/)) issue, it says we need to signoff each commit. Quick way to signoff each commit by using `git commit -s` command Or we can add following in commit message
> 
> ```
> 
> Signed-off-by: Random J Developer <random@developer.example.org>```
> ```

**Review by adriandiglio — APPROVED** [review]
Approved

**Pull request merged**
